- hosts: all
  become: True # Use sudo/root for tasks
  tasks:
    - name: Install packages
      yum:
        name: "nginx"
        state: "present"
    - name: Start nginx server
      service:
        name: nginx
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: /var/lib/jenkins/workspace/JenkinswithAnsible/files/index.html
        dest: /var/www/html/index.html
        remote_src: yes

