- hosts: all
  become: true # Use sudo/root for tasks
  tasks:
    - name: Enable nginx package repository
      command: amazon-linux-extras enable nginx1

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start nginx server
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy static website
      copy:
        src: /var/lib/jenkins/workspace/JenkinswithAnsible/files/index.html #files/index.html  # Path relative to the playbook directory
        dest: /var/www/html/index.html
